// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0b72231d-f19c-44a2-9de1-979b166b7fa0",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_9EBhHdInc",
    "aws_user_pools_web_client_id": "48am7ln8cj1juu9a0s9du9v0mu",
    "oauth": {
        "domain": "amp-test-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/",
        "redirectSignOut": "http://localhost:4200/",
        "responseType": "code"
    }
};


export default awsmobile;
